# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See tools/travis_notes.txt for some guidelines

language: python
sudo: false
cache:
  # See http://docs.travis-ci.com/user/caching/#pip-cache
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/sphinx
    - $HOME/.ccache
addons:
  apt:
    packages:
    - ccache
    - libfreeimage3
    - texlive
    - texlive-latex-extra
    - dvipng
    - python-qt4
env:
  global:
    - GH_REF: github.com/scikit-image/docs.git
    - secure: "MhsXAU5v4ZsJDLbUyVVEQ/F3/aNRSqY3Fa6Slg5mLL9QvxSKrb4vmbI6vyEkT6MennY1rOvUEqnTMa9JqgDveecWt8zxpWTtVoPsh4sWFsUAsza0/Ef73Ct1ApGWNvE+MaG1ivKjSzdd0jZTh3YapYByZMoiK7+1OjRBmKGBdfcq1gRSUj0tugbT60gaWEshBlSTm1pHMzH1u/Y+4bwytLZarGAiabG55w8GXq4h7UryIwDSzwjWhRmNyi/JnWLfdqcYWQzF2iTq4lyH3OoYCaBcDLjZzHZNvQUMxCWedKX/Z/MnWQDukWsDr6x1MKDGaxFsFbB1BIQzq1ribuMySmQ1kk8Qljh7ZVNoSIUoyW/Q+L7jjDpn6sXjpRh0Xg0+yaACbxbZ7LixxHKqPj0fzV0HXjXbfRiba8UUndWY8WVsEZos0q8AiYpFGgfCx5+jCnOMTLlHCMb1X+3p+MSWiMJous9+Lny+KVtAUkles/VPVhXrCRCeiJd9zKc8bWo2nfgy+fCgZvcOI68EbuY9tkLiJV+EK48igMIvDa6kAjlEcYXCebfYgPh0uLPoGMyasHa9EGAiunuiz74aD8sq6E+O604SQpA+1owDBODqQsVMla3OAsrUdNHfVZW/9UjILJ7BvhKF+mlhdZsG0ltskAMiNvb76iQgzPVG8hpsX8s="

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1fea29525e8b929dd7c7
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

matrix:
  include:
    - os: linux
      python: 2.7
      env: PIP_FLAGS="--pre"
    - os: linux
      python: 2.7
      env: WITH_PYAMG=1 MINIMUM_REQUIREMENTS=1 WITH_QT=1
    - os: linux
      python: 3.4
      env: OPTIONAL_DEPS=1 WITH_PYSIDE=1
    - os: linux
      python: 3.5
    - os: linux
      python: 3.5
      env: PIP_FLAGS="--pre"
    # This entry waiting for resolution of issue 2450
    # - os: linux
    #  python: 3.6
    - os: osx
      osx_image: xcode7.3
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=3.5

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source tools/travis_osx_install.sh ; fi
    - ccache -s
    - export PATH=/usr/lib/ccache:${PATH}
    # Attempt to fix bug making virtualenvs for Python 3.6
    - python -m pip install -U pip
    - pip install -U virtualenv
    - source tools/travis_before_install.sh
    - which python; python --version
    - tools/check_bento_build.py
    - tools/build_versions.py
    - tools/check_sdist.py

install:
    - section build
    - python setup.py develop
    - section_end build

script: tools/travis_script.sh

after_success:
    - codecov
    - bash tools/deploy_docs.sh
